masm /T/MX/I.. src\buildbpb,src\buildbpb;
masm /T/MX/I.. src\devclose,src\devclose;
masm /T/MX/I.. src\devopen,src\devopen;
masm /T/MX/I.. src\endaddr,src\endaddr;
masm /T/MX/I.. src\init,src\init;
masm /T/MX/I.. src\input,src\input;
masm /T/MX/I.. src\inputflu,src\inputflu;
masm /T/MX/I.. src\inputsta,src\inputsta;
masm /T/MX/I.. src\ioctlin,src\ioctlin;
masm /T/MX/I.. src\ioctlout,src\ioctlout;
masm /T/MX/I.. src\mediache,src\mediache;
masm /T/MX/I.. src\ndinput,src\ndinput;
masm /T/MX/I.. src\outflush,src\outflush;
masm /T/MX/I.. src\output,src\output;
masm /T/MX/I.. src\outstatu,src\outstatu;
masm /T/MX/I.. src\outverif,src\outverif;
masm /T/MX/I.. src\remmedia,src\remmedia;
lib @driver.lnk
del src\*.obj
