bcc -ml -a -w -ld  ADAMSTST.c anum.lib
bcc -ml -a -w -ld  BISMAIN.c anum.lib
bcc -ml -a -w -ld  DETMAIN.c anum.lib
bcc -ml -a -w -ld  EDICTEST.c anum.lib
bcc -ml -a -w -ld  EDIC1TST.c anum.lib
bcc -ml -a -w -ld  EDIC2TST.c anum.lib
bcc -ml -a -w -ld  EDICSTST.c anum.lib
bcc -ml -a -w -ld  EDIS2TST.c anum.lib
bcc -ml -a -w -ld  EDRKFTST.c anum.lib
bcc -ml -a -w -ld  EGNTHHGS.c anum.lib
bcc -ml -a -w -ld  EGNTJCBI.c anum.lib
bcc -ml -a -w -ld  EGNTPOWR.c anum.lib
bcc -ml -a -w -ld  EGNTVECT.c anum.lib
bcc -ml -a -w -ld  GELMTEST.c anum.lib
bcc -ml -a -w -ld  GSDLTEST.c anum.lib
bcc -ml -a -w -ld  INVMAIN.c anum.lib
bcc -ml -a -w -ld  LAGRMAIN.c anum.lib
bcc -ml -a -w -ld  LSHOTTST.c anum.lib
bcc -ml -a -w -ld  LSQTEST.c anum.lib
bcc -ml -a -w -ld  LUTEST.c anum.lib
bcc -ml -a -w -ld  LVRRTEST.c anum.lib
bcc -ml -a -w -ld  MULLMAIN.c anum.lib
bcc -ml -a -w -ld  NEWTHOR1.c anum.lib
bcc -ml -a -w -ld  PPVTTEST.c anum.lib
bcc -ml -a -w -ld  RAPHSON1.c anum.lib
bcc -ml -a -w -ld  ROMBTEST.c anum.lib
bcc -ml -a -w -ld  SECMAIN.c anum.lib
bcc -ml -a -w -ld  SHOTTEST.c anum.lib
bcc -ml -a -w -ld  SIMPTEST.c anum.lib
bcc -ml -a -w -ld  STEFMAIN.c anum.lib
adamstst
bismain
detmain
edictest
edic1tst
edic2tst
edicstst
egnthhgs
egntjcbi
egntpowr
egntvect
gelmtest
gsdltest
invmain
lagrmain
lshottst
lsqtest
lutest
lvrrtest
mullmain
newthor1
ppvttest
raphson1
edrkftst
rombtest
secmain
shottest
simptest
stefmain
