unit ctuthlp;

interface

const

  hcBintree              = 9;
  hcBitwise              = 10;
  hcCancelBtn            = 34;
  hcDosops               = 39;
  hcExample              = 41;
  hcExCode               = 5;
  hcFCChDirDBox          = 36;
  hcFChangeDir           = 14;
  hcFDosShell            = 15;
  hcFExit                = 16;
  hcFilewrite            = 42;
  hcFOFileOpenDBox       = 30;
  hcFOFiles              = 32;
  hcFOName               = 31;
  hcFOOpenBtn            = 33;
  hcFOpen                = 13;
  hcGraphics             = 6;
  hcIncdecop             = 51;
  hcIntrdemo             = 43;
  hcKeycheck             = 44;
  hcLinklist             = 45;
  hcList                 = 3;
  hcLOpen                = 4;
  hcMatrix               = 52;
  hcNoContext            = 0;
  hcNotes                = 12;
  hcOCColorsDBox         = 38;
  hcOColors              = 27;
  hcOMMouseDBox          = 37;
  hcOMouse               = 26;
  hcOpenBtn              = 35;
  hcOptions              = 25;
  hcOrderptr             = 47;
  hcORestoreDesktop      = 29;
  hcOSaveDesktop         = 28;
  hcPeek                 = 46;
  hcPOpen                = 11;
  hcRunEx                = 40;
  hcSAbout               = 8;
  hcStructures           = 48;
  hcSystem               = 7;
  hcTwolinks             = 49;
  hcUserio               = 50;
  hcViewer               = 2;
  hcWCascade             = 21;
  hcWClose               = 24;
  hcWindows              = 17;
  hcWNext                = 22;
  hcWPrevious            = 23;
  hcWSizeMove            = 18;
  hcWTile                = 20;
  hcWZoom                = 19;

implementation

end.
